ollama:
  host: "http://localhost:11434"
  model: "gemma3:4b"

watchers:
  - name: "screen_watcher"
    enabled: true
    interval: 20
    prompt: "Describe what you see on this screenshot. Focus on open applications, windows, and visible text."

  - name: "system_watcher"
    enabled: true
    interval: 60
    prompt: "Are there any anomalies based on these system statistics?"

actions:
  - name: "console_action"
    enabled: true
